### NfL Stability After Processing
For similar NfL reports: 2025 Lifeng, 2018 Keshavan, 2013 Kuhle; 2023 Rosadas

It is generally agreed that NfL from CSF, plasma, or serum is stable in storage and tolerant of multiple freeze-thaws (2025 Lifeng, 2018 Keshavan, 2023 Rosadas). As explained in the NfL collection stability report, nearly all such studies have relied on detection by the same anti-NfL clones. To this end we checked this is also true of NfL analysed by NfL-PLA which relies on a different antibody set. The results are good and relevant for future use with biobanked samples.

In [1]:
import sys
from pathlib import Path

# Path to the folder, not the .py file
module_dir = Path(r"C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\python")
sys.path.append(str(module_dir))

# Now you can do your import
from ProxiPal import *

OS:				 Windows-11-10.0.26200-SP0
Python version:		 3.12.6 | packaged by conda-forge | (main, Sep 22 2024, 14:01:26) [MSC v.1941 64 bit (AMD64)]
Date and Time:		 2026-06-03 16:14:58
cwd:		 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\user_documents\NfL-PLA Development Paper\NfL-PLA Development Paper Figure Data\GitHub\NfL-iPLA-paper\NfL-iPLA_StorageStability
base_path:		 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal
python_folder:		 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\python
templates_folder:	 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\templates
data_folder:		 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\data
samples_folder:		 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\samples
quality_folder:		 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\quality
user_downloads:		 C:\Users\smith.j\OneDrive - wehi.edu.au\Documents\CFHAC_ProxiPal\ProxiPal\user_downloads

In [2]:
storage_df = pd.read_csv("StorageStability.csv")

In [3]:
view_cols = ['sample_id', 'rep_id', 'SLR; log10(x); exc_std0; ct; mean_ng/L']
storage_df[view_cols]

                  sample_id  rep_id  SLR; log10(x); exc_std0; ct; mean_ng/L
0                  NFL-QC-H       1                                121.6753
1                  NFL-QC-H       1                                121.6753
2               NFL-QC-M 1x       2                                 27.0516
3               NFL-QC-M 1x       2                                 27.0516
4   std1[2000]_progen#62008       3                               2233.2595
..                      ...     ...                                     ...
83            NFL-QC-L Rt2d      39                                  7.7060
84            NFL-QC-L Rt2d      39                                  7.7060
85          NFL-QC-L 4deg2d      40                                  7.8629
86          NFL-QC-L 4deg2d      40                                  7.8629
87                 NFL-QC-H      44                                132.6074

[88 rows x 3 columns]

In [4]:
storage_df_means = storage_df[view_cols].drop_duplicates()
storage_df_means

                   sample_id  rep_id  SLR; log10(x); exc_std0; ct; mean_ng/L
0                   NFL-QC-H       1                                121.6753
2                NFL-QC-M 1x       2                                 27.0516
4    std1[2000]_progen#62008       3                               2233.2595
6              NFL-QC-H RT7d       4                                130.3184
8             NFL-QC-L Rto/n       5                                  7.9819
10           NFL-QC-L 4deg2d      41                                  8.0861
11                  NFL-QC-L       6                                  7.6562
13               NFL-QC-M 2x       7                                 26.8492
15    std1[400]_progen#62008       8                                429.1563
17             NFL-QC-H RT2d       9                                124.4057
19           NFL-QC-H 4deg7d      10                                127.6324
22                  NFL-QC-M      11                                 25.7802
24               NFL-QC-M 3x      12                                 26.3947
26     std1[80]_progen#62008      13                                 79.0237
28            NFL-QC-H Rto/n      14                                111.3778
30           NFL-QC-H 4deg2d      15                                138.7204
32          NFL-QC-L 4dego/n      42                                  8.2366
33               NFL-QC-H 0x      16                                110.5444
35               NFL-QC-L 0x      17                                  8.0530
37     std1[16]_progen#62008      18                                 11.0055
39             NFL-QC-M RT7d      19                                 25.5611
41          NFL-QC-H 4dego/n      20                                137.4945
44               NFL-QC-H 1x      21                                108.5620
46               NFL-QC-L 1x      22                                  6.8241
48    std1[3.2]_progen#62008      23                                  3.4851
50             NFL-QC-M RT2d      24                                 30.8306
52           NFL-QC-M 4deg7d      25                                 27.7532
54                  NFL-QC-H      43                                130.8088
55               NFL-QC-H 2x      26                                128.3754
57               NFL-QC-L 2x      27                                  7.7483
59   std1[0.64]_progen#62008      28                                  0.6320
61            NFL-QC-M Rto/n      29                                 26.9778
63           NFL-QC-M 4deg2d      30                                 27.8386
66               NFL-QC-H 3x      31                                126.9371
68               NFL-QC-L 3x      32                                  7.7483
70  std1[0.128]_progen#62008      33                                  0.1462
72             NFL-QC-L RT7d      34                                  8.0311
74          NFL-QC-M 4dego/n      35                                 29.8569
76                  NFL-QC-H      44                                132.6074
77               NFL-QC-M 0x      36                                 22.8452
79                     empty      37                                  0.1704
81      std1[0]_progen#62008      38                                  0.0165
83             NFL-QC-L Rt2d      39                                  7.7060
85           NFL-QC-L 4deg2d      40                                  7.8629

In [5]:
# calculate recovery based on the 0x sample
QC_H_means = storage_df_means[storage_df_means['sample_id'].str.contains('NFL-QC-H')]
QC_M_means = storage_df_means[storage_df_means['sample_id'].str.contains('NFL-QC-M')]
QC_L_means = storage_df_means[storage_df_means['sample_id'].str.contains('NFL-QC-L')]

In [6]:
# Ensure QC_H_means is an independent copy
QC_H_means = QC_H_means.copy()

# Get the zero concentration value
QC_H_zero = QC_H_means.loc[QC_H_means['sample_id'] == 'NFL-QC-H 0x', 'SLR; log10(x); exc_std0; ct; mean_ng/L'].values[0]

# Calculate recovery %
QC_H_means['recovery %'] = (100 * (QC_H_means['SLR; log10(x); exc_std0; ct; mean_ng/L'] / QC_H_zero)).round(2)
# Display
QC_H_means

,sample_id,rep_id,SLR; log10(x); exc_std0; ct; mean_ng/L,recovery %
0,NFL-QC-H,1,121.6753,110.07
6,NFL-QC-H RT7d,4,130.3184,117.89
17,NFL-QC-H RT2d,9,124.4057,112.54
19,NFL-QC-H 4deg7d,10,127.6324,115.46
28,NFL-QC-H Rto/n,14,111.3778,100.75
30,NFL-QC-H 4deg2d,15,138.7204,125.49
33,NFL-QC-H 0x,16,110.5444,100.00
41,NFL-QC-H 4dego/n,20,137.4945,124.38
44,NFL-QC-H 1x,21,108.5620,98.21
54,NFL-QC-H,43,130.8088,118.33
55,NFL-QC-H 2x,26,128.3754,116.13
66,NFL-QC-H 3x,31,126.9371,114.83
76,NFL-QC-H,44,132.6074,119.96

In [7]:
# Ensure QC_H_means is an independent copy
QC_M_means = QC_M_means.copy()

# Get the zero concentration value
QC_M_zero = QC_M_means.loc[QC_M_means['sample_id'] == 'NFL-QC-M 0x', 'SLR; log10(x); exc_std0; ct; mean_ng/L'].values[0]

# Calculate recovery %
QC_M_means['recovery %'] = (100 * (QC_M_means['SLR; log10(x); exc_std0; ct; mean_ng/L'] / QC_M_zero)).round(2)

# Display
QC_M_means

,sample_id,rep_id,SLR; log10(x); exc_std0; ct; mean_ng/L,recovery %
2,NFL-QC-M 1x,2,27.0516,118.41
13,NFL-QC-M 2x,7,26.8492,117.53
22,NFL-QC-M,11,25.7802,112.85
24,NFL-QC-M 3x,12,26.3947,115.54
39,NFL-QC-M RT7d,19,25.5611,111.89
50,NFL-QC-M RT2d,24,30.8306,134.95
52,NFL-QC-M 4deg7d,25,27.7532,121.48
61,NFL-QC-M Rto/n,29,26.9778,118.09
63,NFL-QC-M 4deg2d,30,27.8386,121.86
74,NFL-QC-M 4dego/n,35,29.8569,130.69
77,NFL-QC-M 0x,36,22.8452,100.00

In [8]:
# Ensure QC_H_means is an independent copy
QC_L_means = QC_L_means.copy()

# Get the zero concentration value
QC_L_zero = QC_L_means.loc[QC_L_means['sample_id'] == 'NFL-QC-L 0x', 'SLR; log10(x); exc_std0; ct; mean_ng/L'].values[0]

# Calculate recovery %
QC_L_means['recovery %'] = (100 * (QC_L_means['SLR; log10(x); exc_std0; ct; mean_ng/L'] / QC_L_zero)).round(2)

# Display
QC_L_means

,sample_id,rep_id,SLR; log10(x); exc_std0; ct; mean_ng/L,recovery %
8,NFL-QC-L Rto/n,5,7.9819,99.12
10,NFL-QC-L 4deg2d,41,8.0861,100.41
11,NFL-QC-L,6,7.6562,95.07
32,NFL-QC-L 4dego/n,42,8.2366,102.28
35,NFL-QC-L 0x,17,8.0530,100.00
46,NFL-QC-L 1x,22,6.8241,84.74
57,NFL-QC-L 2x,27,7.7483,96.22
68,NFL-QC-L 3x,32,7.7483,96.22
72,NFL-QC-L RT7d,34,8.0311,99.73
83,NFL-QC-L Rt2d,39,7.7060,95.69
85,NFL-QC-L 4deg2d,40,7.8629,97.64

In [11]:
# Concatenate the 3 dataframes and manipulate in excel
# Add 'db' column to each before concatenation
QC_H_means['db'] = 'QC_H'
QC_M_means['db'] = 'QC_M'
QC_L_means['db'] = 'QC_L'

# Concatenate lengthwise
StorageStabilityTableData = pd.concat([QC_H_means, QC_M_means, QC_L_means], ignore_index=True)

# Save
StorageStabilityTableData.to_csv('StorageStabilityTableData.csv')

StorageStabilityTableData

,sample_id,rep_id,SLR; log10(x); exc_std0; ct; mean_ng/L,recovery %,db
0,NFL-QC-H,1,121.6753,110.07,QC_H
1,NFL-QC-H RT7d,4,130.3184,117.89,QC_H
2,NFL-QC-H RT2d,9,124.4057,112.54,QC_H
3,NFL-QC-H 4deg7d,10,127.6324,115.46,QC_H
4,NFL-QC-H Rto/n,14,111.3778,100.75,QC_H
5,NFL-QC-H 4deg2d,15,138.7204,125.49,QC_H
6,NFL-QC-H 0x,16,110.5444,100.00,QC_H
7,NFL-QC-H 4dego/n,20,137.4945,124.38,QC_H
8,NFL-QC-H 1x,21,108.5620,98.21,QC_H
9,NFL-QC-H,43,130.8088,118.33,QC_H
10,NFL-QC-H 2x,26,128.3754,116.13,QC_H
11,NFL-QC-H 3x,31,126.9371,114.83,QC_H
12,NFL-QC-H,44,132.6074,119.96,QC_H
13,NFL-QC-M 1x,2,27.0516,118.41,QC_M
14,NFL-QC-M 2x,7,26.8492,117.53,QC_M
15,NFL-QC-M,11,25.7802,112.85,QC_M
16,NFL-QC-M 3x,12,26.3947,115.54,QC_M
17,NFL-QC-M RT7d,19,25.5611,111.89,QC_M
18,NFL-QC-M RT2d,24,30.8306,134.95,QC_M
19,NFL-QC-M 4deg7d,25,27.7532,121.48,QC_M
20,NFL-QC-M Rto/n,29,26.9778,118.09,QC_M
21,NFL-QC-M 4deg2d,30,27.8386,121.86,QC_M
22,NFL-QC-M 4dego/n,35,29.8569,130.69,QC_M
23,NFL-QC-M 0x,36,22.8452,100.00,QC_M
24,NFL-QC-L Rto/n,5,7.9819,99.12,QC_L
25,NFL-QC-L 4deg2d,41,8.0861,100.41,QC_L
26,NFL-QC-L,6,7.6562,95.07,QC_L
27,NFL-QC-L 4dego/n,42,8.2366,102.28,QC_L
28,NFL-QC-L 0x,17,8.0530,100.00,QC_L
29,NFL-QC-L 1x,22,6.8241,84.74,QC_L
30,NFL-QC-L 2x,27,7.7483,96.22,QC_L
31,NFL-QC-L 3x,32,7.7483,96.22,QC_L
32,NFL-QC-L RT7d,34,8.0311,99.73,QC_L
33,NFL-QC-L Rt2d,39,7.7060,95.69,QC_L
34,NFL-QC-L 4deg2d,40,7.8629,97.64,QC_L